//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstructionProgress
    {
        public int progressID { get; set; }
        public Nullable<int> attractionID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> progressDate { get; set; }
    
        public virtual AttractionOrRide AttractionOrRide { get; set; }
    }
}
