//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailRestaurantTransaction
    {
        public int transactionID { get; set; }
        public int foodID { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual RestaurantTransaction RestaurantTransaction { get; set; }
    }
}
