//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int feedbackID { get; set; }
        public Nullable<int> customerID { get; set; }
        public string receiver { get; set; }
        public string title { get; set; }
        public string description { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
