//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaintenanceSchedule()
        {
            this.MaintenanceLog = new HashSet<MaintenanceLog>();
        }
    
        public int scheduleID { get; set; }
        public Nullable<int> attractionID { get; set; }
        public Nullable<System.DateTime> scheduleDate { get; set; }
        public string status { get; set; }
    
        public virtual AttractionOrRide AttractionOrRide { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceLog> MaintenanceLog { get; set; }
    }
}
