//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int taskID { get; set; }
        public Nullable<int> ideaID { get; set; }
        public string status { get; set; }
        public string taskDescription { get; set; }
    
        public virtual Idea Idea { get; set; }
    }
}
